Repository MEME-UMC/MEME_SERVICE, pull requests merged in 2024-01, with the labels that each got.

#4 [Add] Entity 추가, 폴더링, 연관관계 설정
  src/main/java/umc/meme/shop/ShopApplication.java
  src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
  src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
  src/main/java/umc/meme/shop/domain/artist/entity/enums/AvailableTime.java
  src/main/java/umc/meme/shop/domain/artist/entity/enums/Gender.java
  src/main/java/umc/meme/shop/domain/artist/entity/enums/MakeupLocation.java
  src/main/java/umc/meme/shop/domain/artist/entity/enums/Region.java
  src/main/java/umc/meme/shop/domain/artist/entity/enums/WorkExperience.java
  src/main/java/umc/meme/shop/domain/artist/repository/ArtistRepository.java
  src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
  src/main/java/umc/meme/shop/domain/favorite/entity/FavoriteArtist.java
  src/main/java/umc/meme/shop/domain/favorite/entity/FavoritePortfolio.java
  src/main/java/umc/meme/shop/domain/favorite/repository/FavoriteArtistRepository.java
  src/main/java/umc/meme/shop/domain/favorite/repository/FavoritePortfolioRepository.java
  src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
  src/main/java/umc/meme/shop/domain/model/entity/Model.java
  src/main/java/umc/meme/shop/domain/model/entity/enums/PersonalColor.java
  src/main/java/umc/meme/shop/domain/model/entity/enums/SkinType.java
  src/main/java/umc/meme/shop/domain/model/repository/ModelRepository.java
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
  src/main/java/umc/meme/shop/domain/portfolio/entity/PortfolioImg.java
  src/main/java/umc/meme/shop/domain/portfolio/entity/enums/Category.java
  src/main/java/umc/meme/shop/domain/portfolio/repository/PortfolioImgRepository.java
  src/main/java/umc/meme/shop/domain/portfolio/repository/PortfolioRepository.java
  src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
  src/main/java/umc/meme/shop/domain/reservation/entity/enums/ReservationTime.java
  src/main/java/umc/meme/shop/domain/reservation/entity/enums/Status.java
  src/main/java/umc/meme/shop/domain/reservation/repository/ReservationRepository.java
  src/main/java/umc/meme/shop/domain/review/entity/Review.java
  src/main/java/umc/meme/shop/domain/review/entity/ReviewImg.java
  src/main/java/umc/meme/shop/domain/review/repository/ReviewImgRepository.java
  src/main/java/umc/meme/shop/domain/review/repository/ReviewRepository.java
Labels: add ➕

#7 [Add] ApiResponse 통일, Exception handling
  src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
  src/main/java/umc/meme/shop/global/ErrorStatus.java
  src/main/java/umc/meme/shop/global/SuccessStatus.java
  src/main/java/umc/meme/shop/global/exception/GlobalException.java
  src/main/java/umc/meme/shop/global/exception/GlobalExceptionAdvice.java
  src/main/java/umc/meme/shop/global/exception/GlobalExceptionHandler.java
  src/main/java/umc/meme/shop/global/response/ApiResponse.java
Labels: add ➕

#8 [Add] controller mapping
  src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
  src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
  src/main/java/umc/meme/shop/domain/mypage/controller/MyPageController.java
  src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
  src/main/java/umc/meme/shop/global/SuccessStatus.java
  src/main/java/umc/meme/shop/global/response/ApiResponse.java
Labels: add ➕

#15 [Feat] Model ver. MyPage 기능 구현
  src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
  src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
  src/main/java/umc/meme/shop/domain/favorite/repository/FavoriteArtistRepository.java
  src/main/java/umc/meme/shop/domain/favorite/repository/FavoritePortfolioRepository.java
  src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
  src/main/java/umc/meme/shop/domain/model/dto/request/ModelProfileDto.java
  src/main/java/umc/meme/shop/domain/model/entity/Model.java
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
Labels: feat 💜

#17 [Feat] 포트폴리오 생성, 예약 생성, 예약 상태 변경 기능 구현
  src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
  src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
  src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
  src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
  src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
  src/main/java/umc/meme/shop/domain/reservation/dto/request/ReservationRequestDto.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationResponseDto.java
  src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
  src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
  src/main/java/umc/meme/shop/global/ErrorStatus.java
Labels: feat 💜

#19 [Feat] Artist ver. 예약 조회 기능 구현
  src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
  src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
  src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
  src/main/java/umc/meme/shop/domain/portfolio/controller/PortfolioController.java
  src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
  src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationResponseDto.java
  src/main/java/umc/meme/shop/domain/reservation/repository/ReservationRepository.java
  src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
Labels: feat 💜

#24 [Feat] Portfolio Service 관련 기능 추가
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/domain/portfolio/controller/PortfolioController.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/request/CreatePortfolioDto.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
  src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
  src/main/java/umc/meme/shop/domain/portfolio/repository/PortfolioRepository.java
  src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
  src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
  src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
  src/main/java/umc/meme/shop/domain/reservation/repository/ReservationRepository.java
  src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
Labels: feat 💜

#30 [Chore] Model ver. 예약 조회 수정
  src/main/java/umc/meme/shop/domain/model/entity/Model.java
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationResponseDto.java
  src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
  src/test/java/umc/meme/shop/ArtistTest.java
Labels: chore 🧹

#31 [Feat] Artist 프로필 관리/수정 기능 구현
  src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
  src/main/java/umc/meme/shop/domain/artist/dto/request/ArtistProfileDto.java
  src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
  src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
Labels: feat 💜

#35 [Chore] 포트폴리오, 관심 아티스트, 관심 메이크업 조회 수정
  src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
  src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
  src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
  src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
  src/main/java/umc/meme/shop/domain/model/entity/Model.java
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
  src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
  src/main/java/umc/meme/shop/global/ErrorStatus.java
  src/main/java/umc/meme/shop/global/SuccessStatus.java
Labels: chore 🧹

#37 [Feat] 관심 아티스트, 관심 메이크업 삭제 기능 구현
  src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
  src/main/java/umc/meme/shop/domain/favorite/repository/FavoriteArtistRepository.java
  src/main/java/umc/meme/shop/domain/favorite/repository/FavoritePortfolioRepository.java
  src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/global/ErrorStatus.java
  src/main/java/umc/meme/shop/global/SuccessStatus.java
Labels: feat 💜

#41 [Fix] 포트폴리오, 예약 연관관계 수정 / 예외처리 추가
  src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
  src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
  src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
  src/main/java/umc/meme/shop/domain/reservation/repository/ReservationRepository.java
  src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
  src/main/java/umc/meme/shop/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
  src/main/java/umc/meme/shop/global/ErrorStatus.java
Labels: add ➕, fix 🔨

#43 [Fix] Enum List List<String>으로 변경
  src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
  src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
  src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
  src/main/java/umc/meme/shop/domain/artist/entity/enums/Region.java
  src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
  src/main/java/umc/meme/shop/domain/portfolio/entity/enums/Category.java
  src/test/java/umc/meme/shop/ArtistTest.java
Labels: fix 🔨

#46 [Feat] 아티스트 프로필 조회 기능 구현
  src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
  src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
  src/main/java/umc/meme/shop/global/SuccessStatus.java
Labels: feat 💜

#47 [Fix] ID 요청 dto, PathVariable 로 통일, 포트폴리오 수정
  .DS_Store
  src/.DS_Store
  src/main/java/umc/meme/shop/domain/favorite/dto/request/FavoriteArtistDto.java
  src/main/java/umc/meme/shop/domain/favorite/dto/request/FavoritePortfolioDto.java
  src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/domain/portfolio/controller/PortfolioController.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/request/UpdatePortfolioDto.java
  src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
  src/main/java/umc/meme/shop/domain/portfolio/repository/PortfolioRepository.java
  src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
  src/main/java/umc/meme/shop/global/ErrorStatus.java
Labels: fix 🔨

#50 [Add] 예약상태변경 예외처리
  src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
  src/main/java/umc/meme/shop/global/ErrorStatus.java
Labels: add ➕

#51 [Fix] 충돌 해결
  src/main/java/umc/meme/shop/domain/artist/dto/request/ArtistProfileDto.java
  src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
  src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
  src/main/java/umc/meme/shop/domain/artist/entity/enums/AvailableTime.java
  src/main/java/umc/meme/shop/domain/reservation/dto/request/ReservationRequestDto.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationResponseDto.java
  src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
  src/main/java/umc/meme/shop/domain/reservation/entity/enums/ReservationTime.java
  src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
  src/main/java/umc/meme/shop/global/ErrorStatus.java
  src/main/java/umc/meme/shop/global/enums/DayOfWeek.java
  src/main/java/umc/meme/shop/global/enums/Times.java
  src/test/java/umc/meme/shop/ArtistTest.java
Labels: fix 🔨

#53 [Chore] Request Dto 통일
  src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
  src/main/java/umc/meme/shop/domain/artist/dto/request/ArtistProfileDto.java
  src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
  src/main/java/umc/meme/shop/domain/favorite/dto/request/FavoriteArtistDto.java
  src/main/java/umc/meme/shop/domain/favorite/dto/request/FavoritePortfolioDto.java
  src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
  src/main/java/umc/meme/shop/domain/model/dto/request/ModelProfileDto.java
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/domain/portfolio/controller/PortfolioController.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/request/CreatePortfolioDto.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/request/UpdatePortfolioDto.java
  src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
  src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
  src/main/java/umc/meme/shop/domain/reservation/dto/request/AlterReservationDto.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationResponseDto.java
  src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
  src/main/java/umc/meme/shop/domain/review/controller/ReviewController.java
  src/main/java/umc/meme/shop/domain/review/dto/request/ReviewDto.java
  src/main/java/umc/meme/shop/domain/review/dto/request/UpdateReviewDto.java
  src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
Labels: chore 🧹

#55 [Feat] Portfolio Paging 기능 구현
  src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/domain/portfolio/controller/PortfolioController.java
  src/main/java/umc/meme/shop/domain/portfolio/converter/PortfolioConverter.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioPageDto.java
  src/main/java/umc/meme/shop/domain/portfolio/repository/PortfolioRepository.java
  src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
Labels: feat 💜

#60 [Add] 관심 아티스트 조회 페이징 처리
  src/.DS_Store
  src/main/java/umc/meme/shop/domain/artist/converter/ArtistConverter.java
  src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistPageDto.java
  src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
Labels: add ➕

#61 [Feat] 관심 아티스트로 포트폴리오 검색 기능 구현/ 검색 정렬 기능 구현
  src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
  src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
  src/main/java/umc/meme/shop/domain/portfolio/repository/PortfolioRepository.java
  src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationResponseDto.java
  src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
  src/main/java/umc/meme/shop/global/ErrorStatus.java
Labels: feat 💜

#63 [Chore] 포트폴리오, 리뷰 리스트 분리
  src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
  src/main/java/umc/meme/shop/domain/review/controller/ReviewController.java
  src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
Labels: chore 🧹

#64 [Add] 포트폴리오 이미지 한장 저장 및 조회
  src/main/java/umc/meme/shop/domain/portfolio/controller/PortfolioController.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/request/CreatePortfolioDto.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/request/UpdatePortfolioDto.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioImgDto.java
  src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
  src/main/java/umc/meme/shop/domain/portfolio/entity/PortfolioImg.java
  src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
Labels: add ➕

#67 [Feat] 리뷰 삭제 기능 구현
  src/main/java/umc/meme/shop/domain/review/controller/ReviewController.java
  src/main/java/umc/meme/shop/domain/review/dto/request/DeleteReviewDto.java
  src/main/java/umc/meme/shop/domain/review/entity/Review.java
  src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
  src/main/java/umc/meme/shop/global/ErrorStatus.java
  src/main/java/umc/meme/shop/global/SuccessStatus.java
Labels: feat 💜

#69 [Add] 포트폴리오 이미지 완료
  src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
  src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
Labels: add ➕

#68 [Feat] 별점 현황 map 구현
  src/main/java/umc/meme/shop/domain/review/dto/response/ReviewListResponseDto.java
  src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
Labels: feat 💜

#72 [Add]review Img 완료
  src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
  src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
  src/main/java/umc/meme/shop/domain/review/dto/request/ReviewDto.java
  src/main/java/umc/meme/shop/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/umc/meme/shop/domain/review/entity/Review.java
  src/main/java/umc/meme/shop/domain/review/entity/ReviewImg.java
  src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
Labels: add ➕

#71 [Chore] isBlock인 포트폴리오 숨김 처리
  src/main/java/umc/meme/shop/domain/portfolio/dto/request/UpdatePortfolioDto.java
  src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
  src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
  src/main/java/umc/meme/shop/global/ErrorStatus.java
Labels: chore 🧹
