Repository MEME-UMC/MEME_SERVICE, pull requests merged in 2024-02, with the labels that each got.

#81 [Feat] 최근 검색어/ 검색어로 메이크업 검색 기능 구현
  src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
  src/main/java/umc/meme/shop/domain/portfolio/repository/PortfolioRepository.java
  src/main/java/umc/meme/shop/domain/review/dto/response/ReviewImgDto.java
  src/main/java/umc/meme/shop/global/ErrorStatus.java
  src/main/java/umc/meme/shop/global/config/SwaggerConfig.java
  src/test/java/umc/meme/shop/ArtistTest.java
Labels: feat 💜

#83 [Chore] 예약 완료 dto 추가 / 포트폴리오 조회 로직 수정
  src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/domain/portfolio/repository/PortfolioRepository.java
  src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
  src/main/java/umc/meme/shop/domain/reservation/dto/request/ReservationRequestDto.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationCompleteDto.java
  src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
  src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
Labels: chore 🧹

#85 [Add] 아티스트 예약 가능 장소 설정 기능 추가
  src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
  src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ArtistLocationDto.java
  src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
  src/main/java/umc/meme/shop/global/SuccessStatus.java
Labels: add ➕

#87 [Add] 리뷰 페이징 구현, 아티스트 예약 가능 시간 조회
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
  src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
  src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ArtistTimeDto.java
  src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
  src/main/java/umc/meme/shop/domain/review/controller/ReviewController.java
  src/main/java/umc/meme/shop/domain/review/converter/ReviewConverter.java
  src/main/java/umc/meme/shop/domain/review/dto/request/ReviewDto.java
  src/main/java/umc/meme/shop/domain/review/dto/response/ReviewListPageDto.java
  src/main/java/umc/meme/shop/domain/review/dto/response/ReviewListResponseDto.java
  src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
  src/main/java/umc/meme/shop/global/SuccessStatus.java
Labels: add ➕

#94 [Add] 문의하기
  src/main/java/umc/meme/shop/domain/mypage/controller/MyPageController.java
  src/main/java/umc/meme/shop/domain/mypage/dto/request/MypageInquiryDto.java
  src/main/java/umc/meme/shop/domain/mypage/entity/Inquiry.java
  src/main/java/umc/meme/shop/domain/mypage/repository/InquiryRepository.java
  src/main/java/umc/meme/shop/domain/mypage/service/MypageService.java
  src/main/java/umc/meme/shop/global/ErrorStatus.java
  src/main/java/umc/meme/shop/global/SuccessStatus.java
Labels: add ➕

#96 add : 문의하기 완료
  src/main/java/umc/meme/shop/domain/mypage/controller/MyPageController.java
  src/main/java/umc/meme/shop/domain/mypage/dto/request/MypageInquiryDto.java
  src/main/java/umc/meme/shop/domain/mypage/dto/response/MypageInquiryResponseDto.java
  src/main/java/umc/meme/shop/domain/mypage/entity/Inquiry.java
  src/main/java/umc/meme/shop/domain/mypage/service/MypageService.java
  src/main/java/umc/meme/shop/domain/user/User.java
Labels: add ➕

#101 [Feat] 포트폴리오 추천(리뷰 순) 기능 구현
  src/main/java/umc/meme/shop/domain/artist/dto/request/ArtistProfileDto.java
  src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
  src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
  src/main/java/umc/meme/shop/domain/artist/entity/enums/Gender.java
  src/main/java/umc/meme/shop/domain/favorite/dto/response/FavoritePortfolioResponseDto.java
  src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
  src/main/java/umc/meme/shop/domain/model/dto/request/ModelProfileDto.java
  src/main/java/umc/meme/shop/domain/model/entity/Model.java
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/domain/mypage/dto/response/MypageDetailDto.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/request/CreatePortfolioDto.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/request/UpdatePortfolioDto.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
  src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
  src/main/java/umc/meme/shop/domain/portfolio/repository/PortfolioRepository.java
  src/main/java/umc/meme/shop/domain/reservation/dto/request/AlterReservationDto.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ArtistLocationDto.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationResponseDto.java
  src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
  src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
  src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
  src/main/java/umc/meme/shop/domain/user/User.java
  src/main/java/umc/meme/shop/global/SuccessStatus.java
  src/main/java/umc/meme/shop/global/enums/Category.java
  src/main/java/umc/meme/shop/global/enums/Gender.java
  src/main/java/umc/meme/shop/global/enums/MakeupLocation.java
  src/main/java/umc/meme/shop/global/enums/PersonalColor.java
  src/main/java/umc/meme/shop/global/enums/Region.java
  src/main/java/umc/meme/shop/global/enums/SkinType.java
  src/main/java/umc/meme/shop/global/enums/Status.java
  src/main/java/umc/meme/shop/global/enums/WorkExperience.java
  src/test/java/umc/meme/shop/ArtistTest.java
Labels: feat 💜

#103 [Add ] BaseEntity 추가 / 예약 중복 예외 처리
  src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
  src/main/java/umc/meme/shop/domain/common/BaseEntity.java
  src/main/java/umc/meme/shop/domain/favorite/entity/FavoriteArtist.java
  src/main/java/umc/meme/shop/domain/favorite/entity/FavoritePortfolio.java
  src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
  src/main/java/umc/meme/shop/domain/mypage/entity/Inquiry.java
  src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
  src/main/java/umc/meme/shop/domain/portfolio/entity/PortfolioImg.java
  src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
  src/main/java/umc/meme/shop/domain/reservation/repository/ReservationRepository.java
  src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
  src/main/java/umc/meme/shop/domain/review/entity/Review.java
  src/main/java/umc/meme/shop/domain/review/entity/ReviewImg.java
  src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
  src/main/java/umc/meme/shop/domain/user/User.java
  src/main/java/umc/meme/shop/global/ErrorStatus.java
Labels: add ➕

#104 [Feat] 포트폴리오 추천 (최신 순) 기능 구현
  src/main/java/umc/meme/shop/domain/artist/converter/ArtistConverter.java
  src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
  src/main/java/umc/meme/shop/domain/artist/dto/response/SimpleArtistDto.java
  src/main/java/umc/meme/shop/domain/favorite/dto/response/FavoriteArtistPageResponseDto.java
  src/main/java/umc/meme/shop/domain/favorite/dto/response/FavoritePortfolioResponseDto.java
  src/main/java/umc/meme/shop/domain/favorite/dto/response/FavoritePortfolioResponsePageDto.java
  src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/domain/portfolio/converter/PortfolioConverter.java
  src/main/java/umc/meme/shop/domain/portfolio/dto/response/SimplePortfolioDto.java
  src/main/java/umc/meme/shop/global/SuccessStatus.java
Labels: feat 💜

#109 [Refactor] builder 패턴 일괄 적용
  src/main/java/umc/meme/shop/domain/favorite/entity/FavoriteArtist.java
  src/main/java/umc/meme/shop/domain/favorite/entity/FavoritePortfolio.java
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/domain/mypage/controller/MyPageController.java
  src/main/java/umc/meme/shop/domain/mypage/dto/response/MypageDetailDto.java
  src/main/java/umc/meme/shop/domain/mypage/entity/Inquiry.java
  src/main/java/umc/meme/shop/domain/mypage/service/MypageService.java
  src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
  src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ArtistLocationDto.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationCompleteDto.java
  src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
  src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
  src/main/java/umc/meme/shop/domain/review/entity/Review.java
  src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
  src/main/java/umc/meme/shop/domain/user/UserRepository.java
Labels: refactor ✏️

#111 [Fix] 페이징 처리 로직 수정
  src/main/java/umc/meme/shop/domain/model/service/ModelService.java
  src/main/java/umc/meme/shop/domain/mypage/dto/response/MypageInquiryResponseDto.java
  src/main/java/umc/meme/shop/domain/portfolio/controller/PortfolioController.java
  src/main/java/umc/meme/shop/domain/portfolio/repository/PortfolioRepository.java
  src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
  src/main/java/umc/meme/shop/domain/review/controller/ReviewController.java
  src/main/java/umc/meme/shop/domain/review/repository/ReviewRepository.java
  src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
Labels: fix 🔨

#116 [FIX] 메이크업 검색 기능 오류
  src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
Labels: fix 🔨
