Repository MEME-UMC/MEME_SERVICE, pull requests merged in 2024-04, with the labels that each got.

#142 [Refactor] 아티스트 예약 가능 시간 편집 API 분리
  src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
  src/main/java/umc/meme/shop/domain/artist/dto/request/ArtistProfileDto.java
  src/main/java/umc/meme/shop/domain/artist/dto/request/AvailableTimeRequestDto.java
  src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
  src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
  src/main/java/umc/meme/shop/domain/artist/entity/AvailableTime.java
  src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
  src/main/java/umc/meme/shop/global/SuccessStatus.java
Labels: refactor ✏️

#145 [Develop] Reservation, Available Time Refactoring 내용 Main 반영
  src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
  src/main/java/umc/meme/shop/domain/artist/dto/request/ArtistProfileDto.java
  src/main/java/umc/meme/shop/domain/artist/dto/request/AvailableTimeRequestDto.java
  src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
  src/main/java/umc/meme/shop/domain/artist/dto/response/AvailableTimeDto.java
  src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
  src/main/java/umc/meme/shop/domain/artist/entity/AvailableTime.java
  src/main/java/umc/meme/shop/domain/artist/repository/AvailableTimeRepository.java
  src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
  src/main/java/umc/meme/shop/domain/reservation/dto/request/ReservationRequestDto.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ArtistReservationDetailDto.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ModelReservationDetailDto.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationCompleteDto.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationResponseDto.java
  src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
  src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
  src/main/java/umc/meme/shop/domain/review/dto/response/ReviewAvailableListDto.java
  src/main/java/umc/meme/shop/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
  src/main/java/umc/meme/shop/domain/user/User.java
  src/main/java/umc/meme/shop/global/ErrorStatus.java
  src/main/java/umc/meme/shop/global/SuccessStatus.java
  src/main/java/umc/meme/shop/global/enums/Times.java
Labels: fix 🔨

#147 fix: Artist - tempMethod에 workExperience 설정 내용 추가
  src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
Labels: fix 🔨

#155 Feat/#152
  src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
  src/main/java/umc/meme/shop/global/enums/Status.java
Labels: feat 💜

#157 [Feat] Status에 Pending 추가
  src/main/java/umc/meme/shop/global/enums/Status.java
Labels: feat 💜

#160 [Refactor] 예약 상세 조회 API 수정
  src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ArtistReservationDetailDto.java
  src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationDetailDto.java
  src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
Labels: refactor ✏️
